controller_manager:
  ros__parameters:
    update_rate: 100


diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel_names: ["left_wheel_joint"]
  right_wheel_names: ["right_wheel_joint"]
  wheel_separation: 0.35
  wheel_radius: 0.05
  cmd_vel_timeout: 0.5
  publish_rate: 50
